import matplotlib.pyplot as plt
import numpy as np

x1=np.loadtxt('xeu.txt')
yeuv=np.loadtxt('yeuv.txt')
yeux=np.loadtxt('yeux.txt')
plt.plot(x1,yeuv,label="Velocidad")
plt.plot(x1,yeux,label="Desplazamiento")
plt.title("EULER")
plt.legend()
plt.savefig('Euler.PNG')
plt.close()

yrkv=np.loadtxt('yrkv.txt')
yrkx=np.loadtxt('yrkx.txt')
plt.plot(x1,yrkv,label="Velocidad")
plt.plot(x1,yrkx,label="Desplazamiento")
plt.title("Runge Kutta")
plt.legend()
plt.savefig('Runge_Kutta.PNG')
plt.close()

ylfv=np.loadtxt('ylfv.txt')
ylfx=np.loadtxt('ylfx.txt')
xlfx=np.loadtxt('xlfx.txt')
xlfv=np.loadtxt('xlfv.txt')
plt.plot(xlfv-0.01,ylfv,label="Velocidad")
plt.plot(xlfx,ylfx,label="Desplazamiento")
plt.title("Leap Frog")
plt.legend()
plt.savefig('Leap_Frog.PNG')
plt.close()

x1=np.loadtxt('xeua.txt')
yeuv=np.loadtxt('yeuva.txt')
yeux=np.loadtxt('yeux.txt')
plt.plot(x1,yeuv,label="Velocidad")
plt.plot(x1,yeux,label="Desplazamiento")
plt.title("Euler Amortiguado")
plt.legend()
plt.savefig('Euler_a.PNG')
plt.close()

yrkv=np.loadtxt('yrkva.txt')
yrkx=np.loadtxt('yrkxa.txt')
plt.plot(x1,yrkv,label="Velocidad")
plt.plot(x1,yrkx,label="Desplazamiento")
plt.title("Runge Kutta Amortiguado")
plt.legend()
plt.savefig('Runge_Kutta_a.PNG')
plt.close()
